config/routes.rb
Rails.application.routes.draw do

  get 'rounds/complete'
  get 'rounds/in_progress'
  get 'rounds/get_score'=>'rounds#get_score'
  get 'home/index'
  post '/test' => 'home#test'
  get 'rounds/changeview' => 'rounds#change_view'


  resources :rounds, only: [:show, :new, :create,:destroy] do
    resources :scores
  end

  resources :matches, only: [:show, :new, :create,:destroy,:update] do
    resources :invites, only: [:show, :new,:update, :create,:destroy]
   get 'update_leaderboard'
   post 'update_multiple_scores'
   get 'next_hole'
   get 'previous_hole'
   post 'set_current_hole'
  end

  devise_for :members

root to: 'home#index'
end

app/models/match.rb
class Match < ActiveRecord::Base
  after_create :add_scorer_rounds,:set_current_hole
  has_many :member_matches
  has_many :members, :through=> :member_matches
  has_many :invites
  has_many :rounds

def standing
  # self.rounds.sort_by(&:score)
  scored_rounds=[]
  unscored_rounds=[]
  self.rounds.each do |r|
    if r.score==0
      unscored_rounds.push(r)
    else
      scored_rounds.push(r)
    end
  end
  scored_rounds=scored_rounds.sort_by(&:score)
   scored_rounds+unscored_rounds
end

def is_complete?
  self.rounds.each do |r|
    if !r.is_complete?
      return false
    end
  end
  return true
end


def add_member(id)
  m=Member.find(id)
  if m
      self.members.append(m)
      Round.create!(member_id:m.id,track:self.track,match_id:self.id)
  end
end
  def add_scorer_rounds
    if !self.scorer_id.nil?
        Round.create!(member_id:self.scorer_id,track:self.track,match_id:self.id)
    end
  end

  def set_current_hole
    self.update(current_hole:1)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def new
  end

  def create
    m=Match.new
    m.members.append(current_member)
    m.scorer_id=current_member.id
    m.track=params[:match][:track]
    m.save!
    redirect_to m
  end

  def show
    @match=Match.find(params[:id])
    @members=[]
    Member.all.each do |m|
      if current_member.id != m.id
        @members.push(m)
      end
    end
  end

  def update
    @match=Match.find(params[:id])
    @match.update!(update_match_params)
    render 'matches/scripts/post_scores'
  end

  def update_leaderboard
    @match=Match.find(params[:match_id])
    render 'matches/scripts/update_leaderboard'
  end

  def update_multiple_scores
    puts params
    @match=Match.find(params[:match_id])
    params[:ids].each do |id|
      if Score.find(id)
        Score.find(id).update(strokes:params[:strokes][params[:ids].index(id)])
      end
    end
    next_hole
  end

  def next_hole
    @match=Match.find(params[:match_id])
    if @match.current_hole != @match.rounds.first.scores.count
      @match.update(current_hole:@match.current_hole+1)
    else
        @match.update(current_hole:1)
    end
      render 'matches/scripts/post_scores'
  end

  def previous_hole
    @match=Match.find(params[:match_id])
    if @match.current_hole != 1
      @match.update(current_hole:@match.current_hole-1)
    else
        @match.update(current_hole:@match.rounds.first.scores.count)
    end
        render '/matches/scripts/post_scores'
  end

  private
  def match_params
    params.require(:match).permit(:track,:members,:scorer_id)
  end

  def update_match_params
    params.require(:match).permit(:current_hole)
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/partials/_edit_match_scores.html.erb
<h2>Change Hole:</h2>
<%= form_for @match,remote:true do |f| %>
<%= f.collection_select :current_hole,1..@match.rounds.first.scores.count,:to_s,:to_s %>
<%= f.submit 'Change Hole' %><br><br>
<% end %>
<h2>Enter Scores:</h2>
<%= form_tag match_update_multiple_scores_path(@match.id), method: :post, class: "navbar-form navbar-left search-form",remote:true do %>
<table>
  <tr>
    <td >
    <h4>Hole:</h4>
    </td>
    <td>
      <%= @match.current_hole %>
    </td>
  </tr>
  <tr>
    <td >
    <h4>Par:</h4>
    </td>
    <td>
      <%= @match.rounds.first.scores.where(:hole_id=>@match.current_hole).first.hole.par %>
    </td>
  </tr>
  <% for round in @match.rounds %>
  <%= hidden_field_tag "ids[]", round.scores.where(:hole_id=>@match.current_hole).first.id %>
<tr>
  <td>
    <%= label_tag round.member.fname %>
  </td>
  <td>
      <%= text_field_tag "strokes[]", round.scores.where(:hole_id=>@match.current_hole).first.strokes %>
  </td>
</tr>
  <% end %>
  <tr>

    <td colspan="2">
      <div id='arrow-container'>
        <%= link_to  match_previous_hole_path(@match.id),remote:true do%>
        <i class="fa fa-arrow-left fa-3x" ></i>
        <% end %>
        <%= submit_tag "Post Scores" %>
        <%= link_to  match_next_hole_path(@match.id),remote:true do %>
        <i class="fa fa-arrow-right fa-3x" ></i>
        <% end %>
      </div>

    </td>
  </tr>
</table>
<% end %>

app/views/matches/partials/_leaderboard.html.erb
<%= render 'matches/partials/round_info_row' %>

<% @match.standing.each do |r| %>
  <% @round=r %>
  <%= render 'matches/partials/score_row' %>
<% end %>

app/views/matches/partials/_round_info_row.html.erb
  <% round=@match.rounds.first %>
  <div class='lb-row'>
<div class="info-container">
  <div class="lb-data-label hole">
Hole
  </div>
  <% round.scores.each do |s|%>
    <div class="lb-data hole">
      <%= s.hole.name %>
    </div>
  <% end %>
  <div class="lb-data-label hole">
Totals
  </div>
</div>

<div class="info-container">
  <div class="lb-data-label par">
    Par
  </div>
  <% round.scores.each do |s|%>
    <div class="lb-data par">
        <%= s.hole.par %>
    </div>
  <% end %>
  <div class="lb-data-label par">
    <%= round.par %>
  </div>
</div>

</div>

app/views/matches/partials/_score_row.html.erb
<div class="lb-row">
  <div class="info-container">
    <div class="lb-data-label member">
      <%= @round.member.fname %>
    </div>
    <% @round.scores.each do |s|%>

      <div class="lb-data <%= 'bogey' if s.is_bogey? %> <%= 'double-bogey' if s.is_double_bogey? or s.is_other? %> <%= 'birdie' if s.is_birdie? %> <%= 'eagle' if s.is_eagle? or  s.is_albatros?%>">
          <div class="score-border">
            <span>
              <%= s.strokes %>
            </span>
          </div>
      </div>

    <% end %>
    <div class="lb-data-label member">
      <span>
        <%= @round.score %>
      </span>
    </div>
    </div>
  </div>