config/routes.rb
Rails.application.routes.draw do

  get 'rounds/complete'
  get 'rounds/in_progress'
  get 'rounds/get_score'=>'rounds#get_score'
  get 'home/index'
  post '/test' => 'home#test'
  get 'rounds/changeview' => 'rounds#change_view'


  resources :rounds, only: [:show, :new, :create,:destroy] do
    resources :scores
  end

  resources :matches, only: [:show, :new, :create,:destroy,:update] do
    resources :invites, only: [:show, :new,:update, :create,:destroy]
   get 'update_leaderboard'
   post 'update_multiple_scores'
   get 'next_hole'
   get 'previous_hole'
   post 'set_current_hole'
  end

  devise_for :members

root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @completed_rounds=[]
    @incomplete_rounds=[]
    if current_member
      current_member.rounds.each do |r|
        if r.is_complete?
          @completed_rounds.push(r)
        else
          @incomplete_rounds.push(r)
        end
      end
    end
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if not current_member %>
  <%= link_to "Sign Up",  new_member_registration_path, class: "btn btn-primary" %>
  <%= link_to "Sign In",   new_member_session_path, class: "btn btn-primary" %>
<% end %>

<% if current_member %>
<%= link_to "New Round",   new_round_path, class: "btn btn-primary",remote:true %>
<%= link_to "New Match",   new_match_path, class: "btn btn-primary"%>
<div id="member-info">
<h3><%= current_member.fname %></h3>
</div>
<div id="new-round">

</div>
<div id="rounds-stage">
  <div id="in-progress-rounds">
    <%= render 'rounds/shared/in_progress'  %>
  </div>
  <div id="complete-rounds">
    <%= render 'rounds/shared/complete'  %>
  </div>
</div>
<h1>Current Matches</h1>
<div class="member-matches">
  <% current_member.matches.each do |m| %>
    <% m.members.each do |mem| %>
    <%= mem.fname %>
    <% end %>
    <%= link_to "Show Match",   match_path(m.id), class: "btn btn-primary"%><br>

  <% end %>
</div>
<div class="member-invites">
  <h1>Invites</h1>
  <% current_member.invites.each do |i| %>
    <%= Member.find(i.match.scorer_id).fname %>
    <%= link_to "Accept", match_invite_path(i.match.id,i.id),
          :method => :patch %>

  <% end %>
</div>

<% end %>

app/views/home/index.js.erb
$('#complete-rounds').html("<%= j(render(partial: '/rounds/complete')) %>")
$('#in-progress-rounds').html("<%= j(render(partial: '/rounds/in_progress')) %>")