config/routes.rb
Rails.application.routes.draw do

  get 'rounds/complete'
  get 'rounds/in_progress'
  get 'rounds/get_score'=>'rounds#get_score'
  get 'home/index'
  post '/test' => 'home#test'
  get 'rounds/changeview' => 'rounds#change_view'


  resources :rounds, only: [:show, :new, :create,:destroy] do
    resources :scores
  end

  resources :matches, only: [:show, :new, :create,:destroy,:update] do
    resources :invites, only: [:show, :new,:update, :create,:destroy]
   get 'update_leaderboard'
   post 'update_multiple_scores'
   get 'next_hole'
   get 'previous_hole'
   post 'set_current_hole'
  end

  devise_for :members

root to: 'home#index'
end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :member
  belongs_to :match
  has_many :scores
  # validates_inclusion_of :track, in: Choices['track']
  # validates_inclusion_of :tee, in: Choices['tee']
  after_create :add_scores

  def number_of_holes
    self.scores.count
  end

  def holes_remaining
    unplayed=0
    self.scores.each do |s|
      if !s.strokes
        unplayed+=1
      end
    end
    unplayed
  end

  def yardage
    yards=0
    self.scores.each do |s|
      if s.hole.yardage[self.tee]
        yards+=s.hole.yardage[self.tee]
      end
    end
    yards
  end

  def holes_played
    played=0
    self.scores.each do |s|
      if s.strokes
        played+=1
      end
    end
    played
  end

  def score
    score=0
    self.scores.each do |s|
      if s.strokes
        score+=s.strokes
      end
    end
    score
  end

  def par
    par=0
    self.scores.each do |s|
      par+=s.hole.par
    end
    par
  end

  def current_par_status
    current_par=0
    self.scores.each do |s|
      if s.strokes
        current_par+=s.offset
      end
    end
    current_par
  end

  def over_under
    score= self.score-self.par
    if score > 0
      score= '+' + score.to_s
    else
      score
    end
  end

  def is_complete?
    self.scores.each do |s|
      if !s.strokes
        return false
      end
    end
    return true
  end

  def next_hole_id
    if !self.is_complete?
      self.scores.each do |s|
        if !s.strokes
          if s.hole.id > 18
            hole_id=s.hole_id-18
          else
            hole_id=s.hole_id
          end
        return hole_id
        end
      end
    end
    nil
  end

  def score_by_hole_id(h)
    self.scores.each do |s|
      if s.hole_id==h
          return s
      end
    end
    return nil
  end

private
  def add_scores
    if self.track.include? 'w'
      i=1
      while i<10
        Score.create(hole_id:i,round_id:self.id)
        i+=1
      end
    end
    if self.track.include? 'b'
      i=10
      while i<19
        Score.create(hole_id:i,round_id:self.id)
        i+=1
      end
    end
    if self.track.include? 'r'
      i=19
      while i<28
        Score.create(hole_id:i,round_id:self.id)
        i+=1
      end
    end
  end


end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  def new
  end

  def show
    @round=Round.find(params[:id])
  end

  def create
    r=Round.create!(create_round_params)
    redirect_to round_path :id=>r.id
  end

  def change_view
    @view=params[:view]
    @round=Round.find(params[:id])
    render 'rounds/js/viewswitcher'
  end

  def complete
    render :layout => false
  end

  def in_progress
    render :layout => false
  end

private
def create_round_params
  params.require(:round).permit(:track,:tee,:member_id)
end
def score_params
  params.require(:score).permit(:strokes,:id)
end

def update_score_params
  params.permit(:strokes)
end
end

app/helpers/rounds_helper.rb
module RoundsHelper
  def hole_name(short)
    name=''
    case short[1].downcase
      when 'r'
        course_name=' Red'
      when 'b'
        course_name=' Blue'
      when 'w'
        course_name=' White'
    end
    name=short[0]+course_name
  end

end

app/views/rounds/shared/_complete.html.erb
<h1>Completed Rounds:</h1>

<% @completed_rounds.each do |r| %>
<%= format_date(r.created_at) %>:
  <%= r.score %>
    <%= link_to "Show Round",round_path(:id=>r.id)%><br>
<% end %>

app/views/rounds/shared/_holes.html.erb
<%@round.scores.each do |r|  %>
<div class='hole-button'>
  <% if r.strokes %>
    <%= link_to hole_name(r.hole.name), round_score_path(:round_id=>@round.id,:id=>r.id), remote: true%>
  <% else %>
    <%= link_to hole_name(r.hole.name), round_score_path(:round_id=>@round.id,:id=>r.id),class:'missing-strokes-btn', remote: true%>
  <% end %>
</div>
<% end %>

app/views/rounds/shared/_in_progress.html.erb
<h1>In Progress Rounds:</h1>
<% @incomplete_rounds.each do |r| %>
<%= format_date(r.created_at) %><br>
The next hole is:  <%= r.next_hole_id %>
    <%= link_to "Show Round",round_path(:id=>r.id)%><br>
<% end %>

app/views/rounds/shared/_info.html.erb
<% if @round %>
Score:  <%= @round.score %><br>
Par:<%= @round.par %><br>
Yardage:  <%= @round.yardage %>
<% end %>

app/views/rounds/shared/_new.html.erb
<div id="new-round-container">
    <%= form_for Round.new do |f| %>
    <%= f.hidden_field :member_id, :value => current_member.id %>
    <%= f.collection_select :track,Choices['track'],:to_s,:to_s %>
    <%= f.collection_select :tee,Choices['tee'],:to_s,:to_s %>
    <%= f.submit %>
    <% end %>
</div>

app/views/rounds/shared/_scoreform.html.erb
<% if @score %>
<div class="score-form">
<%= form_for @score, :url => round_score_path(@score.round_id,@score.id),remote:true do |f| %>
<table class="score-table">
  <tr>
    <td>
      <%= f.label 'Strokes' %>
    </td>
    <td>
      <%= f.collection_select :strokes,1..10,:to_s,:to_s %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.label 'GIR?' %>
    </td>
    <td>
      <%= f.check_box :gir %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.label 'Fairway?' %>
    </td>
    <td>
      <%= f.check_box :fairway %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.label 'Putts' %>
    </td>
    <td>
      <%= f.collection_select :putts,0..4,:to_s,:to_s %>
    </td>
  </tr>
  <tr>
    <td colspan="2">
      <%= f.submit %>
    </td>
  </tr>
</table>
<% end %>
</div></div>
<% end %>